CREATE TABLE Employees (
    EmployeeID INT PRIMARY KEY AUTO_INCREMENT,
    FullName VARCHAR(255) NOT NULL,
    ContactDetails VARCHAR(255),
    Login VARCHAR(50) UNIQUE NOT NULL,
    Password VARCHAR(50) NOT NULL,
    Role VARCHAR(20) NOT NULL
);

CREATE TABLE Shifts (
    ShiftID INT AUTO_INCREMENT PRIMARY KEY,
    ShiftName VARCHAR(255) NOT NULL,
    StartDate TIME NOT NULL,
    EndDate TIME NOT NULL
);

CREATE TABLE ShiftEmployee (
    ShiftEmployeeID INT AUTO_INCREMENT PRIMARY KEY,
    EmployeeID INT,
    ShiftID INT,
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID) ON DELETE CASCADE,
    FOREIGN KEY (ShiftID) REFERENCES Shifts(ShiftID) ON DELETE CASCADE
);

CREATE TABLE Menu (
    MenuItemID INT AUTO_INCREMENT PRIMARY KEY,
    DishName VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL
);


CREATE TABLE Orders (
    OrderID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT,
    ShiftID INT,
    OrderStatus VARCHAR(20) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Employees(EmployeeID) ON DELETE CASCADE,
    FOREIGN KEY (ShiftID) REFERENCES Shifts(ShiftID) ON DELETE CASCADE
);

CREATE TABLE OrderItem (
    OrderItemID INT AUTO_INCREMENT PRIMARY KEY,
    OrderID INT,
    MenuItemID INT,
    Quantity INT,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID) ON DELETE CASCADE,
    FOREIGN KEY (MenuItemID) REFERENCES Menu(MenuItemID) ON DELETE CASCADE
);
